/* Generated By:JavaCC: Do not edit this line. CarumaLangLexerConstants.java */
package AnalizadorLexico;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CarumaLangLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CARUMA = 5;
  /** RegularExpression Id. */
  int HOLAHOLA = 6;
  /** RegularExpression Id. */
  int BYEBYE = 7;
  /** RegularExpression Id. */
  int CAECLIENTE = 8;
  /** RegularExpression Id. */
  int SINOCAE = 9;
  /** RegularExpression Id. */
  int PAPOI = 10;
  /** RegularExpression Id. */
  int PARAPAPOI = 11;
  /** RegularExpression Id. */
  int STOPPLEASE = 12;
  /** RegularExpression Id. */
  int DIOS = 13;
  /** RegularExpression Id. */
  int DIOSNO = 14;
  /** RegularExpression Id. */
  int INTCHELADA = 15;
  /** RegularExpression Id. */
  int GRANITO = 16;
  /** RegularExpression Id. */
  int CADENA = 17;
  /** RegularExpression Id. */
  int CARACTER = 18;
  /** RegularExpression Id. */
  int ESTOES = 19;
  /** RegularExpression Id. */
  int MENORIGUALITOQUE = 20;
  /** RegularExpression Id. */
  int MAYORIGUALITOQUE = 21;
  /** RegularExpression Id. */
  int IGUALITO = 22;
  /** RegularExpression Id. */
  int MAYORQUE = 23;
  /** RegularExpression Id. */
  int MENORQUE = 24;
  /** RegularExpression Id. */
  int PONER = 25;
  /** RegularExpression Id. */
  int QUITAR = 26;
  /** RegularExpression Id. */
  int SALEMAS = 27;
  /** RegularExpression Id. */
  int SALEMENOS = 28;
  /** RegularExpression Id. */
  int ABRIENDO = 29;
  /** RegularExpression Id. */
  int CERRANDO = 30;
  /** RegularExpression Id. */
  int OPEN = 31;
  /** RegularExpression Id. */
  int CLOSE = 32;
  /** RegularExpression Id. */
  int AHIVA = 33;
  /** RegularExpression Id. */
  int MIXCHELADA = 34;
  /** RegularExpression Id. */
  int NUMERITO = 35;
  /** RegularExpression Id. */
  int TEXTOLITERAL = 36;
  /** RegularExpression Id. */
  int LETRALITERAL = 37;
  /** RegularExpression Id. */
  int INVALID = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"Caruma\"",
    "\"holahola\"",
    "\"byebye\"",
    "\"CaeCliente\"",
    "\"SiNoCae\"",
    "\"papoi\"",
    "\"paraPapoi\"",
    "\"stopPlease\"",
    "\"DIOS\"",
    "\"DIOSNO\"",
    "\"intCHELADA\"",
    "\"granito\"",
    "\"cadena\"",
    "\"caracter\"",
    "\"=\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "<MIXCHELADA>",
    "<NUMERITO>",
    "<TEXTOLITERAL>",
    "<LETRALITERAL>",
    "<INVALID>",
  };

}
